name: Lancer programme Java

on:
  push:
    branches: [ main ]

jobs:
    job0:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
    job1:
        needs: job0
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 25
              uses: actions/setup-java@v5
              with:
                java-version: 25
                distribution: temurin
                cache: maven

    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Compilation
              run: mvwn compile

    job3:
        needs: job2
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: mvnw test